image: docker:19.03.0

stages:
  - build

build:
  image: python:3.9-slim-bullseye
  stage: build
  before_script:
      - apt update && apt install python3-dev python3-setuptools python3-psycopg2
      - pip install --upgrade pip
      - pip uninstall PIL
  script:
      - pip3 install --upgrade --target=package -r requirements.txt
  artifacts:
    name: "media-processor-$CI_COMMIT_SHORT_SHA"
    exclude:
      - .gitlab-ci.yml
      - .git/**/*
      - .git
      - README.md
      - requirements.txt
    paths:
        - ./*
