image: docker:19.03.0

variables:
  BUILD_FILE: "media-processor.zip"

stages:
  - test
  - build
  - deploy

test-compileall:
  stage: test
  image: python:3.9-slim-bullseye
  script: 
    - echo "Checking that python files compile"
    - python -m compileall  *.py

build-zip:
  stage: build
  image: "alpine:3.16"
  before_script:
    - apk add --update zip
  script:
    - zip -r $BUILD_FILE *.py
  dependencies:
    - test-compileall
  artifacts:
    paths:
      - ./$BUILD_FILE

deploy-prod:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws lambda update-function-code --function-name PROD-iseplifeMediaProcessing --zip-file "fileb://${BUILD_FILE}"
  dependencies:
    - build-zip
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'

deploy-dev:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws lambda update-function-code --function-name DEV-iseplifeMediaProcessing --zip-file "fileb://${BUILD_FILE}"
  dependencies:
    - build-zip
  rules:
    - if: '$CI_COMMIT_REF_NAME == "staging"'


