image: docker:19.03.0

stages:
  - build


build:
  image: python:3.7.2-slim-stretch
  stage: build
  before_script:
      - apt-get install python3-dev python3-setuptools
      - pip install --upgrade pip
      - mkdir -p package
  script: 
      - pip3 install --upgrade -r --target=package requirements.txt 
  artifacts:
    name: "media-processor-$CI_COMMIT_SHORT_SHA"
    exclude:
      - .gitlab-ci.yml
      - .git/**/*
      - .git
      - README.md
      - requirements.txt
    paths:
        - ./*
