image: docker:19.03.0

stages:
  - build-python-deps

build-python-deps:
  image: lambci/lambda:build-python3.8
  stage: build-python-deps
  before_script:
      - pip install --upgrade pip
  script:
      - pip3 install -U -t . -r requirements.txt
      - svn export -q https://github.com/jkehler/awslambda-psycopg2/trunk/psycopg2-3.8 && mv psycopg2-3.8 psycopg2
  artifacts:
    name: "media-processor-deps-layer-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    exclude:
      - .gitlab-ci.yml
      - .git/**/*
      - .git
      - .gitignore
      - README.md
      - requirements.txt
    paths:
        - ./*
