image: docker:19.03.0

stages:
  - build

build:
  image: python:3.9-slim-bullseye
  stage: build
  before_script:
      - pip install --upgrade pip
  script:
      - pip3 install -U -t package -r requirements.txt
  artifacts:
    name: "media-processor-$CI_COMMIT_SHORT_SHA"
    exclude:
      - .gitlab-ci.yml
      - .git/**/*
      - .git
      - README.md
      - requirements.txt
    paths:
        - ./*
